# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
